
PROXY_DST_ID_1 = 11
PROXY_DST_ID_2 = 12

MID_PROXY_PORT_1 = 1
MID_PROXY_PORT_2 = 2
MID_PROXY_PORT_3 = 3
MID_PROXY_PORT_4 = 4

APP_TYPE_GENERAL = 0
APP_TYPE_WEB = 1

SVC_TYPE_PROXY = 0
SVC_TYPE_FIREWALL = 1
SVC_TYPE_QOS = 2
SVC_TYPE_LOAD_BALANCE = 3

SVC_ACT_DEFAULT = 0
SVC_ACT_FIREWALL = 1

QOS_TOP = 0
QOS_HIGH = 1
QOS_MEDIUM = 2
QOS_LOW = 3